services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ../secrets:/run/secrets:ro  # ← bon chemin vu que docker-compose.yml est dans srcs/
    networks:
      - inception

volumes:
  mariadb_data:

networks:
  inception:
    driver: bridge

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    restart: always
    volumes:
      - wordpress_data:/var/www/html
      - ../secrets:/run/secrets:ro
    environment:
      - DB_HOST=mariadb
      - DB_NAME=wordpress
      - DB_USER_FILE=/run/secrets/credentials.txt
      - DB_PASS_FILE=/run/secrets/db_password.txt
    networks:
      - inception
    expose:
      - "9000"

volumes:
  mariadb_data:
  wordpress_data:

networks:
  inception:
    driver: bridge

