services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
      - ../secrets:/run/secrets:ro
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password.txt
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
      - ./../secrets:/run/secrets:ro
    environment:
      DB_HOST: mariadb
      DB_NAME: wordpress
      DB_USER_FILE: /run/secrets/credentials.txt
      DB_PASS_FILE: /run/secrets/db_password.txt
    networks:
      - inception
    expose:
      - "9000"

  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception


volumes:
  mariadb_data:
  wordpress_data:

networks:
  inception:
    driver: bridge


